#!/bin/sh -e

script_dir="$(dirname $0)"
readonly INVALID_ARGUMENT=1

program_name=$(basename $0)
memory=4096M
cpus=4
disk=40G
vm_name=docker-multipass
image=lts

print_help() {
  local prog_name=$1
  local exit_code=$2
  local err_msg=$3

  if [ -n "$err_msg" ]; then
    echo >&2 "$err_msg"
    echo >&2 ""
  fi

  echo "docker-multipass create, create a VM for use with docker."
  echo ""
  echo "Usage: "
  echo "    docker-multipass $prog_name [-n|--name NAME][-c|--cpus N] [-m|--mem xyzwM] [-d|--disk xyG]"
  echo ""
  echo "  -c,--cpus        Integer. Number of cpus provided to the docker VM. [$cpus]"
  echo "  -d,--disk        Amount of disk provided to the docker VM. [$disk]"
  echo "  -h,--help        Print this help text."
  echo "  -m,--mem         Amount of memory provided to the docker VM. [$memory]"
  echo "  -n,--name        Name of the docker VM. [$vm_name]"
  echo ""
  exit $exit_code
}

# Read config
config_file="$HOME/.docker-multipass-config"
if [ -f "$config_file" ]; then
  set -o allexport; source "$config_file"; set +o allexport
fi

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -c|--cpus)
      cpus=$2
      shift
      shift
      ;;
    -m|--mem)
      memory=$2
      shift
      shift
      ;;
    -d|--disk)
      disk=$2
      shift
      shift
      ;;
    -n|--name)
      vm_name=$2
      shift
      shift
      ;;
    -i|--image)
      image=$2
      shift
      shift
      ;;
    -h|--help)
      print_help "$program_name" 0
      ;;
    *)
      print_help "$program_name" $INVALID_ARGUMENT "Invalid argument $key"
      ;;
  esac
done
set -- "${POSITIONAL[@]}"

multipass launch \
  --name $vm_name \
  --cpus $cpus \
  --mem $memory \
  --disk $disk \
  $image

multipass mount ${HOME} $vm_name:${HOME}

multipass transfer "$script_dir/"bootstrap-in-vm.sh $vm_name:bootstrap-in-vm.sh
multipass transfer "$script_dir/"unattended.conf $vm_name:unattended.conf
multipass exec $vm_name -- sudo bash bootstrap-in-vm.sh
multipass exec $vm_name -- rm bootstrap-in-vm.sh
multipass exec $vm_name -- rm unattended.conf

multipass restart $vm_name

DOCKER_INSTANCE=$(multipass info $vm_name | grep IPv4 | awk '{split($0,a," "); print a[2]}')

export DOCKER_HOST="tcp://$DOCKER_INSTANCE:2375"

echo ""
echo "Insert the following into your profile:
export DOCKER_HOST=tcp://$DOCKER_INSTANCE:2375"
echo ""
