#!/bin/bash

readonly program_name="$(basename $0)"
vm_name="docker-multipass"

print_help() {
  local prog_name=$1
  local exit_code=$2
  local err_msg=$3

  if [ -n "$err_msg" ]; then
    echo >&2 "$err_msg"
    echo >&2 ""
  fi

  echo "docker-multipass $prog_name, starts a multipass VM."
  echo ""
  echo "Usage: "
  echo "    docker-multipass $prog_name [-n|--name NAME]"
  echo ""
  echo "  -h,--help        Print this help text."
  echo "  -n,--name        Name of the docker VM. [$vm_name]"
  echo ""
  exit $exit_code
}

# Read config
config_file="$HOME/.docker-multipass-config"
if [ -f "$config_file" ]; then
  set -o allexport; source "$config_file"; set +o allexport
fi

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -n|--name)
      vm_name=$2
      shift
      shift
      ;;
    -h|--help)
      print_help $program_name 0
      ;;
    *)
      print_help $program_name $INVALID_ARGUMENT "Invalid argument $key"
      ;;
  esac
done
set -- "${POSITIONAL[@]}"

multipass start "$vm_name"
